extend class PDAMenu
{
	const BASE_RES_WIDTH = 640;
	const BASE_RES_HEIGHT = 400;

	void PDAConfig(void)
	{
		DoPDAConfig
		(
			// Set PDA menu resolution
			BASE_RES_WIDTH,
			BASE_RES_HEIGHT,

			// Set PDA menu font
			"PDAFONT",

			// Overall UI colour
			Color(118, 118, 206),

			// Font colour
			Font.CR_LightBlue,

			// Unread PDA color
			Font.CR_LightBlue,

			// Read PDA color
			Font.CR_Black
		);
	}
}
